<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="author" content="Fred Swartz (www.fredosaurus.com)"/>
    <link rel="stylesheet" type="text/css" href="../notes.css"/>
    <script type="text/JavaScript" src="../notes.js"></script>
    <title>C++ Notes: Exception Test</title>
</head>
<body>
<h1><a href="../index.html">C++ Notes</a>: Exception Test</h1>
<p>The following program illustrates exception handling.</p>
<ul>
<li class="compact">Shows how many different types can be thrown.</li>
<li class="compact">Shows how subclasses can be caught by superclasses, if not caught earlier.</li>
<li class="compact">Shows how any exception can be caught with <code>catch (...)</code>.</li>
</ul>

<h3>Source program</h3>
<table border='0' summary=''><tr><td valign='top'><pre class='example2'>
  1 
  2 
  3 
  4 
  5 
  6 
  7 
  8 
  9 
 10 
 11 
 12 
 13 
 14 
 15 
 16 
 17 
 18 
 19 
 20 
 21 
 22 
 23 
 24 
 25 
 26 
 27 
 28 
 29 
 30 
 31 
 32 
 33 
 34 
 35 
 36 
 37 
 38 
 39 
 40 
 41 
 42 
 43 
 44 
 45 
 46 
 47 
 48 
 49 
 50 
 51 
 52 
 53 
 54 
 55 
 56 
 57 
 58 
 59 
 60 
 61 
 62 
 63 
 64 
 65 
 66 
 67 
 68 
 69 
 70 
 71 
 72 
 73 
 74 
 75 
 76 
 77 
 78 
 79 
 80 
 81 
 82 
 83 
 84 
 85 
 86 
 87 
 88 
 89 
 90 
 91 
 92 
 93 
 94 
 95 
 96 
</pre></td><td valign='top'>
<div class="example"><pre>
// exceptions/exception-test.cpp - Test exceptions.
// 2004-02-10 - Fred Swartz

//==================================== includes
#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
#include &lt;string&gt;
using namespace std;

//================================================ prototypes
void generateException(int whichException);

//====================================================== main
int main() {
    for (int i=1; ; i++) {  // Loop forever
        try {
            cout &lt;&lt; i;
            generateException(i);
        } catch (out_of_range orex) {
            cout &lt;&lt; "    Catching: out_of_range "&lt;&lt; orex.what() &lt;&lt; endl;
        } catch (const char* mess) {
            cout &lt;&lt; "    Catching: const char* " &lt;&lt; mess &lt;&lt; endl;
        } catch (string smess) {
            cout &lt;&lt; "    Catching: string " &lt;&lt; smess &lt;&lt; endl;
        } catch (int iex) {
            cout &lt;&lt; "    Catching: int " &lt;&lt; iex &lt;&lt; endl;
        } catch (runtime_error rex) {
            cout &lt;&lt; "    Catching: runtime_error " &lt;&lt; rex.what() &lt;&lt; endl;
        } catch (exception eex) {
            cout &lt;&lt; "    Catching: " &lt;&lt; eex.what() &lt;&lt; endl;
        } catch (...) {
            cout &lt;&lt; "    ERROR: Nobody caught this!" &lt;&lt; endl;
        }
    }            

    system("PAUSE");   // Keep Dev-C++ window open
    return 0;
}

//========================================= generateException
void generateException(int whichException) {
    switch (whichException) {
        
    case 1:
        cout &lt;&lt; "  Throwing out_of_range()" &lt;&lt; endl;
        throw out_of_range("out_of_range meaningful comment");
        break;
        
    case 2:
        cout &lt;&lt; "  Throwing exception()   // Can't specify comment" &lt;&lt; endl;
        throw exception();  // Doesn't take comment text.
        break;
        
    case 3:
        cout &lt;&lt; "  Throwing underflow_error  // caught by base class (runtime_error)" &lt;&lt; endl;
        throw underflow_error("underflow_error");
        break;
        
    case 4:
        cout &lt;&lt; "  Throwing runtime_error" &lt;&lt; endl;
        throw runtime_error("a comment");
        break;
        
    case 5:
        cout &lt;&lt; "  Throwing length_error   // caught be super-super-class (exception)" &lt;&lt; endl;
        throw length_error("length_error");
        break;
        
    case 6:
        cout &lt;&lt; "  Throwing int" &lt;&lt; endl;
        throw 26;
        break;
        
    case 7:
        cout &lt;&lt; "  Throwing const char*" &lt;&lt; endl;
        throw "This is a const char*";
        break;
        
    case 8:
        cout &lt;&lt; "  Throwing string" &lt;&lt; endl;
        throw string("I'm a string");
        break;
        
    case 9:
        cout &lt;&lt; "  Throwing float" &lt;&lt; endl;
        throw 3.14159;
        break;
        
    default:
        cout &lt;&lt; "  Throwing up" &lt;&lt; endl;
        system("PAUSE");
        exit(0);
    }
    return;

}
</pre></div>
</td></tr></table>


<h3>Output</h3>
<p>The following output is from Dev-C++ (using gcc version ?).
MS Visual C++ v6 gives a similar result, differing only in what catching <code>exception</code> prints.</p>
<pre class="file">
1  Throwing out_of_range()
    Catching: out_of_range out_of_range meaningful comment
2  Throwing exception()   // Can't specify comment
    Catching: St9exception
3  Throwing underflow_error  // caught by base class (runtime_error)
    Catching: runtime_error underflow_error
4  Throwing runtime_error
    Catching: runtime_error a comment
5  Throwing length_error   // caught be super-super-class (exception)
    Catching: St9exception
6  Throwing int
    Catching: int 26
7  Throwing const char*
    Catching: const char* This is a const char*
8  Throwing string
    Catching: string I'm a string
9  Throwing float
    ERROR: Nobody caught this!
10  Throwing up
</pre>

<script type="text/JavaScript">footer("2004");</script>
</body>

</html>
